kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: topology-aware-scheduler-leader-elect
  namespace: tas-scheduler
subjects:
  - kind: ServiceAccount
    name: topology-aware-scheduler
    namespace: tas-scheduler
roleRef:
  kind: Role
  name: topology-aware-scheduler-leader-elect
  apiGroup: rbac.authorization.k8s.io
