kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: topology-aware-scheduler-as-kube-scheduler
  namespace: kube-system
subjects:
  - kind: ServiceAccount
    name: topology-aware-scheduler
    namespace: tas-scheduler
roleRef:
  kind: Role
  name: extension-apiserver-authentication-reader
  apiGroup: rbac.authorization.k8s.io
