name: CI E2E

on:
  pull_request:
    branches:
      - 'main'

defaults:
  run:
    shell: bash

jobs:
  e2e-positive:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: setup golang
      uses: actions/setup-go@v2
      id: go
      with:
        go-version: 1.17

    - name: build test binary
      run: |
        make build-e2e

    - name: build tool
      run: |
        make

    - name: create K8S kind cluster
      run: |
        # kind is part of 20.04 image, see: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
        kind version
        # see image listing in https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1
        kind create cluster --config=hack/kind-config-e2e-positive.yaml --image kindest/node:v1.23.0@sha256:49824ab1727c04e56a21a5d8372a402fcd32ea51ac96a2706a12af38934f81ac
        kubectl label node kind-worker node-role.kubernetes.io/worker=''

    - name: run E2E tests
      run: |
        _out/e2e.test -ginkgo.focus='\[PositiveFlow\]' -ginkgo.v

  e2e-negative:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: setup golang
      uses: actions/setup-go@v2
      id: go
      with:
        go-version: 1.17

    - name: build test binary
      run: |
        make build-e2e

    - name: build tool
      run: |
        make

    - name: create K8S kind cluster
      run: |
        # kind is part of 20.04 image, see: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
        kind version
        # see image listing in https://github.com/kubernetes-sigs/kind/releases/tag/v0.11.1
        kind create cluster --config=hack/kind-config-e2e-negative.yaml --image kindest/node:v1.23.0@sha256:49824ab1727c04e56a21a5d8372a402fcd32ea51ac96a2706a12af38934f81ac
        kubectl label node kind-worker node-role.kubernetes.io/worker=''

    - name: run E2E tests
      run: |
        _out/e2e.test -ginkgo.focus='\[NegativeFlow\]' -ginkgo.v
