name: CI E2E

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  e2e-positive:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: setup golang
      uses: actions/setup-go@v2
      id: go
      with:
        go-version: 1.17

    - name: build test binary
      run: |
        make build-e2e

    - name: build tool
      run: |
        make

    - name: create K8S kind cluster
      run: |
        # kind is part of 20.04 image, see: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
        kind create cluster --config=hack/kind-config-e2e-positive.yaml --image kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
        kubectl label node kind-worker node-role.kubernetes.io/worker=''

    - name: run E2E tests
      run: |
        _out/e2e.test -ginkgo.focus='\[PositiveFlow\]'

  e2e-negative:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout sources
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: setup golang
      uses: actions/setup-go@v2
      id: go
      with:
        go-version: 1.17

    - name: build test binary
      run: |
        make build-e2e

    - name: build tool
      run: |
        make

    - name: create K8S kind cluster
      run: |
        # kind is part of 20.04 image, see: https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
        kind create cluster --config=hack/kind-config-e2e-negative.yaml --image kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
        kubectl label node kind-worker node-role.kubernetes.io/worker=''

    - name: run E2E tests
      run: |
        _out/e2e.test -ginkgo.focus='\[NegativeFlow\]'
